apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp

spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
